### ISSUE TITLE
Make readme.md

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/open-data-pvnet#10]

**Comment by jcamier** [comment]
@peterdudfield I sent you a slack message about my last commit. I had assumed main was already created and hence pushed to develop to make a PR to go from develop to main, however since no branches were created yet, develop is now default. I am assuming you can make the change as I don't have permissions to do so.

Here is my proposed readme which is already live 😮[README.md](https://github.com/user-attachments/files/18049759/README.md)

**Comment by jcamier** [comment]
Here is a preview

# 🌞 Open Source Solar Forecasting Project – Volunteers Welcome! 🌞

## Scope

We're building an open-source solar forecasting pipeline to integrate with the OCF's [PVNet](https://github.com/openclimatefix/pvnet) using publicly available data to predict solar generation at the national level, starting with the UK. Eventually, we aim to achieve **global coverage**! 🌍

Tasks include:
- Identifying gridded Numerical Weather Prediction (NWP) datasets.
- Downloading and transforming NWP data into the preferred Zarr format.
- Acquiring solar generation target data via APIs (e.g., PVlive's solar generation and capacity API).
- Creating pipelines for batching data and ML model experimentation.
- Deploying the model to the cloud.

We will begin in the UK to benchmark against OCF results and expand to other countries as the project progresses. 😄

---

## Volunteer Skills/Roles Needed

We are looking for volunteers with the following skills:
- **Data Engineers**: For data acquisition, curation,transformation, and storage.
- **Machine Learning Enthusiasts**: To experiment, train, and evaluate models.
- **Software Developers**: Especially those with Python expertise.
- **Cloud Computing Experts**: For deploying and scaling the model.
- **DevOps Specialists**: To streamline workflows and maintain infrastructure.

---

If you're passionate about **renewable energy, open-source collaboration, and sustainability**, please join us in advancing solar forecasting solutions for a better future! 🌍☀️✨

**Comment by jcamier** [comment]
@peterdudfield I think this is done and now on the `main` branch. Are you okay if we move this to done?

**Comment by peterdudfield** [comment]
> @peterdudfield I think this is done and now on the `main` branch. Are you okay if we move this to done?

Can you do this?

**Comment by peterdudfield** [comment]
@all-contributors please add @peterdudfield for projectManagement
@all-contributors please add @Sukh-P for projectManagement
@all-contributors please add @jcamier for ideas

**Comment by jcamier** [comment]
@peterdudfield looks good to me. Just merged the PR. I recommend we move this to done.
