### ISSUE TITLE
Start creating project dependencies

### ISSUE THREAD

**Issue by jcamier** [openclimatefix/open-data-pvnet#22]

**Comment by jcamier** [comment]
@peterdudfield @Sukh-P do you want to make this project that someone can just pip install from PyPI ?

I thought this would be another good place for me to get this project setup by new years (Jan 1 2025) target. I can set this up with `pipenv`, `venv` or `poetry`. 

What do you guys recommend as your preferred approach. Also, what is the beginning version of Python will we support?

**Comment by jcamier** [comment]
Decision was made to pip install from PyPI. Supporting Python >=3.9

**Comment by jcamier** [comment]
Started the pyproject.toml by copying and pasting most from PVNet. I removed some and added more...this is very rough draft to start a conversation with anyone who has an opinion/advice on this repo at this early stage...

https://github.com/openclimatefix/open-data-pvnet/blob/feature/issue-22/pyproject.toml

**Comment by jcamier** [comment]
@peterdudfield on PVNet you guys use flake8 as a dependency in the pyproject.toml. But our coding standards tell us to use ruff which is definitely the favorite of most in the Python community. Are you okay if we remove flake8 and just use ruff?

Also, you have mypy for static type checker. I rather not use it on this project at this time. Or, does OCF devs love it? I am personally not a fan of it until the code base becomes so large with so many teams that you need something like it as a double check. Thoughts?

**Comment by peterdudfield** [comment]
yea, just ruff is good. Yea thats fine. 
I think we can add it in later, when its more mature

**Comment by jcamier** [comment]
@peterdudfield @Sukh-P I think this is basically ready to be uploaded to PyPI. 

I ran 

pip install -e .

pip install -e ".[dev]"

pytest

twine upload --repository testpypi dist/*

And all passed. Take a look and let me know what you think?

https://github.com/openclimatefix/open-data-pvnet/tree/feature/issue-22

**Comment by peterdudfield** [comment]
Hi @jcamier 

Thats great - thanks. Ill have a look at the PR. 

Do you think we should wait a bit before uploading the pypi, once we have some code in it? Im just aware we are uploading something pretty empty right now. Or perhaps Ive missed something

**Comment by peterdudfield** [comment]
Now reading the maintaince.md, I would leave it out of PR #25 and do it in a separate one, if thats ok? Then we can get #25 merged

**Comment by jcamier** [comment]
@peterdudfield 
No problem. Just removed `maintainers.md`

I have been on many teams and learned to be flexible as there are many ways to successfully deliver a product. I want to work with your way of doing things and accommodate your work stream. Just trying to make consistent, incremental progress often to help this project be a success for PVNet, the OCF team and volunteers. Most of my attempts right now are to get this to a state where most volunteers can jump in the first week of January, after the announcement, if they are so inclined.

**Comment by peterdudfield** [comment]
Thanks @jcamier 

if you think its useful to release to pypi, then lets do that. I can probably do a PR with that stuff, as Ive done it for the various other repos

**Comment by peterdudfield** [comment]
Do you mind making a seperate issue for that i.e. release to pypi?

**Comment by jcamier** [comment]
@peterdudfield I made a new issue called `Release Project to PyPI`, issue #26 for the time you want to officially push this to PyPI. Also, removed how to pip install from the readme as that would most like go on issue #26.

I think this should be okay to merge into main now?
https://github.com/openclimatefix/open-data-pvnet/pull/25

I know you approved it but made comments afterwards, hence why I have not merged yet. Please advise? Thank you.

**Comment by peterdudfield** [comment]
Yep, merge away
