### ISSUE TITLE
How to get started document

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/open-data-pvnet#9]
Things to include
- Whats the idea? Why should you work on it
- Link to github project board
- examples of how to use zarr
- Linked to useful OCF repos
- How to get invovled

**Comment by Jayavardhan-7** [comment]
hey iam intrested to work on it?can I do it?

**Comment by jcamier** [comment]
@Jayavardhan-7 sure. Welcome any help on the getting started. This is the readme I started.[getting_started.md](https://github.com/user-attachments/files/18015567/getting_started.md)

**Comment by jcamier** [comment]
Here is the getting_started.md file for you to view:

# Solar Forecasting Volunteer Onboarding

Welcome to the Solar Forecasting project! This document will introduce you to the key concepts and knowledge needed to contribute effectively.

## Table of Contents
1. [Introduction to Solar Forecasting](#introduction-to-solar-forecasting)
2. [What is NWP Data?](#what-is-nwp-data)
3. [Understanding Zarr Format](#understanding-zarr-format)
4. [Target Data: What is UK PVlive?](#target-data-what-is-uk-pvlive)
5. [Basics of Machine Learning for Solar Forecasting](#basics-of-machine-learning-for-solar-forecasting)
6. [APIs and Data Retrieval](#apis-and-data-retrieval)
7. [Data Pipelines for Solar Forecasting](#data-pipelines-for-solar-forecasting)
8. [Benchmarks and Comparisons](#benchmarks-and-comparisons)
9. [Geographical Adaptability](#geographical-adaptability)
10. [Key Tools and Technologies](#key-tools-and-technologies)
11. [Common Terminology](#common-terminology)
12. [Expected Knowledge and Skills](#expected-knowledge-and-skills)
13. [How This Project Fits into Renewable Energy](#how-this-project-fits-into-renewable-energy)

---

## Introduction to Solar Forecasting
Solar forecasting is the process of predicting the amount of solar energy that will be generated over a specific period. Understanding this helps optimize renewable energy systems and integrate them with the grid.

---

## What is NWP Data?
**Numerical Weather Prediction (NWP)** data uses mathematical models of the atmosphere and oceans to forecast weather. It predicts various atmospheric conditions such as temperature, pressure, wind speed, humidity, precipitation type and amount, cloud cover, and sometimes even surface conditions and air quality—all of which are crucial for solar forecasting.

https://en.wikipedia.org/wiki/Numerical_weather_prediction


---

## Understanding Zarr Format

**zarr** is a relatively new, cloud-based data format designed to improve access to N-dimensional arrays. It provides an effective way to store large N-dimensional data in the cloud, with access facilitated through predefined chunks. Zarr can be viewed as the cloud-based counterpart to HDF5/NetCDF files, as it follows a similar data model. However, unlike NetCDF or HDF5, which store data in a single file, Zarr organizes data as a directory containing compressed binary files for chunks of data, alongside metadata stored in external JSON files.

The semantic mapping from the NetCDF Data Model to the Zarr Data Model is as follows:

| NetCDF Data Model | Zarr V2 Data Model                |
|-------------------|-----------------------------------|
| File              | Store                             |
| Group             | Group                             |
| Variable          | Array                             |
| Attribute         | User Attribute                    |
| Dimension         | Not supported as a native feature |

A Zarr array can be stored in any storage system that supports a key/value interface. In this system:

A key is an ASCII string.
A value is an arbitrary sequence of bytes.
Supported operations include:
Read: Retrieve the sequence of bytes associated with a key.
Write: Set the sequence of bytes associated with a key.
Delete: Remove a key/value pair.
Currently, Zarr V2 is the stable version, while Zarr V3 is considered experimental.
https://wiki.earthdata.nasa.gov/display/ESO/Zarr+Format

---

## Target Data: What is UK PVlive?
UK PVlive provides national solar generation data, accessible via API. This data serves as a "ground truth" for training and evaluating solar forecasting models.

---

## Basics of Machine Learning for Solar Forecasting
Discover key ML concepts such as data splitting, feature engineering, and model evaluation, all tailored to the solar forecasting domain.

---

## APIs and Data Retrieval
Learn how to use APIs to fetch solar generation data and capacity information, critical for building datasets.

---

## Data Pipelines for Solar Forecasting
Explore how pipelines prepare and batch data for machine learning models, making training and testing efficient.

---

## Benchmarks and Comparisons
Understand the importance of benchmarking and how our models compare to existing solutions.

---

## Geographical Adaptability
This project isn't limited to the UK currently but will be expanded to other global regions in the future. Learn how it can be adapted to other regions and data sources.

---

## Key Tools and Technologies
Familiarize yourself with tools like Python, pandas, and open-source libraries like `ocf-datasample`.

---

## Common Terminology
Learn the meanings of key terms like Grid Supply Point (GSP), solar irradiance, and capacity factors.

---

## Expected Knowledge and Skills
An overview of the skills contributors should have or be willing to learn, such as Python programming and data analysis.

---

## How This Project Fits into Renewable Energy
Understand the broader impact of this work and its contribution to a sustainable future.

---

Thank you for joining us on this journey to advance solar forecasting and renewable energy solutions!

**Comment by peterdudfield** [comment]
This looks great for a `getting started`. @jcamier would you be able to do a first version of a main readme.md as well?

**Comment by jcamier** [comment]
Sure. @peterdudfield . I am assuming the readme would just be a summary of the project and our goal with a link to to the getting_started guide then?

**Comment by Jayavardhan-7** [comment]
Thank you, @peterdudfield, for providing such a great markdown file! Should I go ahead and add it to the repository as the README.md, or are there any additional files or updates you'd like me to include?

**Comment by jcamier** [comment]
@Jayavardhan-7 @peterdudfield I plan on creating a new markdown readme file today about the general scope of the project for the initial landing page. As well as, having `a getting_started.md` file/link to allow those who are interested to dig deeper and explore. Or, we could just combine in one if you guys think that would be better? I like to keep the readme smaller to not overwhelm most of the public/volunteers and make it a speedy read but then give links that allow others to dive deeper if they are so interested etc, Zettelkasten/Obsidian style
https://obsidian.rocks/getting-started-with-zettelkasten-in-obsidian/

**Comment by jcamier** [comment]
@Jayavardhan-7 @peterdudfield this issue is also tied to the readme. 
https://github.com/orgs/openclimatefix/projects/36/views/1?pane=issue&itemId=89809990&issue=openclimatefix%7Copen-data-pvnet%7C10

Would like to get consensus on the readme first. I am proposing to have a readme that is really simple and more a call to action. Then, this getting_started.md to have a lot of links and resources where volunteers can find a lot of answers to their questions. In my experience with open source and working with volunteers, they get excited about jumping in but often get lost. We often that have the time to answer all these questions, so hopefully this could help them get up-to-speed quickly and allow them to contribute.

Here is my initial branch for this:
https://github.com/openclimatefix/open-data-pvnet/tree/docs/issue-9

**Comment by jcamier** [comment]
Just added a link from the readme to getting started and coding style dependencies to the repo and to the `getting_started.md`

https://github.com/openclimatefix/open-data-pvnet/blob/docs/issue-9/getting_started.md

**Comment by peterdudfield** [comment]
> Just added a link from the readme to getting started and coding style dependencies to the repo and to the `getting_started.md`
> 
> https://github.com/openclimatefix/open-data-pvnet/blob/docs/issue-9/getting_started.md

Nice, shall we merge this in? Im keen for the little and often PRs

**Comment by jcamier** [comment]
@peterdudfield just merged in main branch with updated readme. I like the idea of many quick iterations to move fast initially. As the project grows, we can add more tests and checks as it gets closer to being used in production. I do still have more changes for the getting_started.md but we could merge this one to start the base and then create issues for each of the sections if you want?

Let me know if you want me to raise a PR for this?

**Comment by peterdudfield** [comment]
Yea, I would get that in now, and then add to it as we go

**Comment by jcamier** [comment]
Merged. Moved to done.

**Comment by siddharth7113** [comment]
> Just added a link from the readme to getting started and coding style dependencies to the repo and to the `getting_started.md`
> 
> https://github.com/openclimatefix/open-data-pvnet/blob/docs/issue-9/getting_started.md

Hi @jcamier 

I was looking through the repo, and  found out ,you wrote `getting_started.md` , I just wanted to say thanks, It reduced a lot of friction especially for beginners starting in a new code base, Very well written, I wish something like this exsist on all of OSS repos, it makes contributions  especially as a beginner a lot easier.

**Comment by jcamier** [comment]
Thanks @siddharth7113 . That was my hope to try to make on-boarding other open source contributors easier.
